#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02

if [ ! -x "$(command -v haproxy)" ]; then
    sudo apt-get -y update
    sudo apt-get -y install haproxy
fi

echo "
frontend 101877-lb-01
        bind *:80
        mode http
        default_backend server
backend server
        balance roundrobin
        mode http
        server 168714-web-01 100.25.102.18 check
        server 168714-web-02 54.237.30.210 check" | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy restart
