#!/usr/bin/env bash
# This script configures HAProxy 2.6 on a server
# Configs: listen on port 80 & distrubte traffic between web-01 and web-02
# using roundrobin algorithm
add-apt-repository ppa:vbernat/haproxy-1.5 -y
apt-get update -y
apt-get dist-upgrade -y
apt-get install haproxy -y
echo -e "\nfrontend myfrontend\n\tbind *:80\n\tdefault_backend myservers\n\nbackend myservers\n\tbalance roundrobin\n\tserver web-01 100.25.102.18\n\tserver web-02 54.237.30.210" >> /etc/haproxy/haproxy.cfg
service haproxy restart
