#!/usr/bin/env bash
# A Script that configure Nginx to run and listen to all the server's active IPv4 IPs
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
kill "$(pgrep 'nginx' | head -1)"
